name: Mongo Demo

on:
  schedule:
  - cron: '0 5 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions-cicd
    steps:
      - name: install the RapidFort CLI tools
        run:   curl  https://frontrow.rapidfort.com/cli/ | bash

      - name: authenticate
        env:
          RF_ACCESS_ID: ${{ secrets.RF_ACCESS_ID }}
          RF_SECRET_ACCESS_KEY: ${{ secrets.RF_SECRET_ACCESS_KEY }}
        run: rflogin

      - name: pull the latest mongo image
        run: docker pull mongo:latest

      - name: run rfstub to generate the stub. this creates a new image, mongo:latest-rfstub
        run: rfstub mongo:latest

      - name: run the stub. add the SYS_PTRACE capability so that RapidFort can trace the runtime behavior
        run: |
          docker run -d --rm -eMONGODB_ROOT_PASSWORD=my_pass -p8081:8081 --name my-rf-test --cap-add=SYS_PTRACE mongo:latest-rfstub
          sleep 15

      - name: run some tests to exercise the application. 
        run: |
          curl https://raw.githubusercontent.com/rapidfort/community-images/main/community_images/common/tests/test.mongo > test.mongo
          docker cp test.mongo my-rf-test:/tmp/test.mongo
          docker exec -i my-rf-test /bin/bash -c "mongosh admin --authenticationDatabase admin -u root -p my_pass --file /tmp/test.mongo"

      - name: stop the container
        run: docker stop my-rf-test

      - name: run rfharden to optimize and secure the image. this creates a new image, mongo:latest-rfhardened
        run: rfharden mongo:latest-rfstub

      - name: check out the various images we created
        run: docker images | grep mongo

      - name: run the hardened image and test it again
        run: |
          docker run -d --rm -eMONGODB_ROOT_PASSWORD=my_pass -p8081:8081 --name mongo-hardened mongo:latest-rfhardened
          sleep 15
          docker cp test.mongo mongo-hardened:/tmp/test.mongo
          docker exec -i mongo-hardened /bin/bash -c "mongosh admin --authenticationDatabase admin -u root -p my_pass --file /tmp/test.mongo"

      - name: for more information, please view the Getting Started documentation
        run: echo "https://docs.rapidfort.com/getting-started/docker"
